awesome: &awesome Font Awesome 6 Free:style=solid:pixelsize=14
awesome_brands: &awesome_brands Font Awesome 6 Brands:pixelsize=16


bar:
  height: 26
  location: top
  background: 282828ff # https://www.useotools.com/color-converter
  foreground: ebdbb2ff
  font: Cascadia Code SemiBold:pixelsize=18
  spacing: 10

  left:
   - river:
       anchors:
        - base: &river_base
           margin: 6
           conditions:
            id == 1: {string: {text: I }}  
            id == 2: {string: {text: II }}  
            id == 3: {string: {text: III }}  
            id == 4: {string: {text: IV }}  
            id == 5: {string: {text: V }}  
            id == 6: {string: {text: VI }}  
            id == 7: {string: {text: VII }}  
            id == 8: {string: {text: VIII }}  
            id == 9: {string: {text: IX}}  
            id == 10: {string: {text: X}}  
       content:
        map:
          on-click:
            left: sh -c "riverctl set-focused-tags $((1 << ({id} - 1)))"
            right: sh -c "riverctl toggle-focused-tags $((1 << ({id} -1)))"
            middle: sh -c "riverctl toggle-view-tags $((1 << ({id} -1)))"
          conditions:
            state == urgent:
              map:
                <<: *river_base
            state == focused:
              map:
                <<: *river_base
                deco: {background: {color: 665c5fff}}
            state == visible:
              map:
                <<: *river_base
            state == unfocused:
              map:
                <<: *river_base
            state == invisible:
              map:
                conditions:
                  ~occupied: {empty: {}}
                  occupied: {map: {<<: *river_base}}

  center:
    - river:
        title: {string: {text: '{title}', max: 80}}
        content: {empty: {}}

  right:
    - network:
        name: enp42s0
        content:
          map:
            conditions:
              ~carrier: {empty: {}}
              carrier:
                map:
                  default: {string: {text: , font: *awesome}}
                  conditions:
                    state == up && ipv4 != "":
                      - {string: {text: , font: *awesome}}
                      - {string: {text: "{ipv4}"}}

    - network:
        name: wlo1
        poll-interval: 1000
        content:
          map:
            default: {string: {text: , font: *awesome}}
            conditions:
              state == up:
                map:
                  default:
                    - string: {text: , font: *awesome}
                    - string: {text: "{ssid}"}

                  conditions:
                    ipv4 == "":
                      - string: {text: , font: *awesome}
                      - string: {text: "{ssid}"}
    - cpu:
        poll-interval: 2500
        content:
          map:
            conditions:
              id < 0:
                - string: {text: , font: Font Awesome 6 Free:style=solid}
                - string: {text: "{cpu}%"}
    - mem:
        poll-interval: 2500
        content:
          - string: {text: , font: Font Awesome 6 Free:style=solid}
          - string: {text: "{percent_used}%"}

    - clock:
        time-format: "%H:%M"
        content:
          - string: {text:  , font: "Font Awesome 6 Free:style=solid:size=12"}
          - string: {text: "{date} ", right-margin: 5}
          - string: {text:  , font: "Font Awesome 6 Free:style=solid:size=12"}
          - string: {text: "{time} "}

